services:
  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - .:/var/lib/postgresql/RS-data
    networks:
      - reservation_system_default
  nginx:
    image: nginx
    # restart: always
    ports:
      - '3003:3003'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - reservation_system_default
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - .:/app
    ports:
      - '3002:3002'
    depends_on:
      - postgres
    command: pm2-runtime start server.js --watch
    networks:
      - reservation_system_default
networks:
  reservation_system_default:
    driver: bridge
