version: "3"

services:
  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/RS-data
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"  # 如果你需要从外部访问 Redis，可以映射 Redis 默认端口

  nginx:
    image: nginx
    # restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
