version: "3"

services:
  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    volumes:
      - .:/var/lib/postgresql/RS-data
  nginx:
    image: nginx
    # restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
