services:
  postgres:
    image: postgres
    # restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: test
    ports:
      - '5432:5432'
    volumes:
      - .:/var/lib/postgresql/RS-data
  nginx:
    image: nginx
    # restart: always
    ports:
      - '3003:3003'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
    # restart: always
    ports:
      - '3002:3002'
    depends_on:
      - postgres
